/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ccb_dev_interfaces_Qrcode */

#ifndef _Included_com_ccb_dev_interfaces_Qrcode
#define _Included_com_ccb_dev_interfaces_Qrcode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ccb_dev_interfaces_Qrcode
 * Method:    open_qrcode_dev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ccb_dev_interfaces_Qrcode_open_1qrcode_1dev
  (JNIEnv *, jclass);

/*
 * Class:     com_ccb_dev_interfaces_Qrcode
 * Method:    close_qrcode_dev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ccb_dev_interfaces_Qrcode_close_1qrcode_1dev
  (JNIEnv *, jclass);

/*
 * Class:     com_ccb_dev_interfaces_Qrcode
 * Method:    read_qrcode_dev
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ccb_dev_interfaces_Qrcode_read_1qrcode_1dev
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ccb_dev_interfaces_Qrcode
 * Method:    touch_qrcode_dev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ccb_dev_interfaces_Qrcode_touch_1qrcode_1dev
  (JNIEnv *, jclass);

/*
 * Class:     com_ccb_dev_interfaces_Qrcode
 * Method:    set_port_speed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ccb_dev_interfaces_Qrcode_set_1port_1speed
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ccb_dev_interfaces_Qrcode
 * Method:    set_coded_format
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ccb_dev_interfaces_Qrcode_set_1coded_1format
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
